site_name: KPF
site_description: Public documentation for the Keck Planet Finder (KPF) instrument at the W. M. Keck Observatory.
site_author: Josh Walawender
repo_url: https://github.com/KeckObservatory/KPFTranslator/
repo_name: KPFTranslator
edit_uri: ''

remote_branch: gh-pages

theme:
  name: readthedocs
  titles_only: true
  highlightjs: true
  hljs_languages:
    - yaml
    - python

markdown_extensions:
  - codehilite

plugins:
- search
- mkdocstrings

nav:
  - "KPF Home": index.md
  - "Instrument Info":
    - "Instrument Subsystems":
      - "Spectrograph": spectrograph.md
      - "FIU": fiu.md
      - "Guider": guider.md
      - "Ca H&K Spectrograph": cahk.md
      - "Exposure Meter": exposuremeter.md
      - "Calibration Bench": calbench.md
      - "Agitator": agitator.md
    - "Instrument Specifications":
      - "Detectors": detectors.md
      - "Sensitivity": sensitivity.md
      - "Data Format": dataformat.md
      - "KPF vs. HIRES": KPFvsHIRES.md
    - "Instrument Software": KPFTranslator.md
  - "Observing with KPF":
    - "Afternoon Setup": afternoonsetup.md
    - "OB Parameters": OBparameters.md
    - "Observing Procedures": observingprocedures.md
    - "Retrieve Data in Real Time": https://koa.ipac.caltech.edu/rti-gui/login
    - "Data Reduction": kpfdrp.md
  - "General Observing Info": 
    - "Weather":
      - "MK Weather Center": http://mkwc.ifa.hawaii.edu/forecast/mko/index.cgi
      - "Keck Cloud Cameras": https://www3.keck.hawaii.edu/skycams/CloudCamTimelapse.html
    - "Useful Keck Pages":
      - "Telescope Schedule": https://www2.keck.hawaii.edu/observing/keckSchedule/keckSchedule.php
      - "Target List Format": https://www.keck.hawaii.edu/realpublic/inst/common/starlist.html
      - "Keck Instruments": http://www2.keck.hawaii.edu/inst/
      - "General Keck Observing Info": https://www.keckobservatory.org/observing/
      - "Pre-observing Checklist": https://www.keck.hawaii.edu/realpublic/inst/kpf/pre-observing_checklist.html
      - "Remote Observing": http://www2.keck.hawaii.edu/inst/common/mainland_observing.html
    - "Telescope Specifications":
      - "Limits": https://www.keck.hawaii.edu/realpublic/inst/common/TelLimits.html
      - "Telescope Info": http://www2.keck.hawaii.edu/observing/kecktelgde/ktelinstupdate.pdf
    - "Keck Policies":
      - "Split Nights": http://www2.keck.hawaii.edu/observing/SplitNights.html
      - "Remote Observing": http://www2.keck.hawaii.edu/inst/common/mainland_observing.html
      - "Other Policies": http://www2.keck.hawaii.edu/observing/policies.html
  - "After Your Observing Run":
    - "Post-observing Comment Form": https://www2.keck.hawaii.edu/inst/PILogin/login.php
    - "Retrieve Your Data":
      - "Retrieve Data from KOA": https://koa.ipac.caltech.edu/
      - "Retrieve Data using PyKOA": http://koa.ipac.caltech.edu/UserGuide/PyKOA/notebooks/PyKOA_KPF_introduction.html
      - "Data Proprietary Period": http://www2.keck.hawaii.edu/realpublic/koa/public/KOA_data_policy.pdf
    - "Acknowledging Keck": https://www2.keck.hawaii.edu/observing/keck_authors.html
    - "Acknowledging KPF": references.md
  - "Technical Documentation":
    - "Operations Scripts": scripts/scripts.md
    - "Troubleshooting": https://keckobservatory.atlassian.net/wiki/external/Yzg1NGM2NzVkMjUwNGRmMGE4ODBiNThiNWY1YzViY2U
