site_name: KPF

plugins:
- search
- mkdocstrings

nav:
  - Home: index.md
  - Pre-Observing: pre-observing.md
  - Observing: observing.md
  - Scripts: scripts.md
  - Post-Observing: post-observing.md
