Template_Name: kpf_configuration
Template_Version: 1.0

ConfigName: 4x30s_SimulCal     # Identifier for this Configuration
Object: default                # User settable comment. Use 'default' to automatically set to TargetName
# Science Detectors
nExp: 4                        # Number of exoposures in the OB
ExpTime: 30                    # Exposure time of the main spectrometer and CaH&K. See Exposure Meter section below.
# Instrument Configuration 
TriggerCaHK: False             # Include CaHK in exposure (True/False)
TriggerGreen: True             # Include Green CCD in exposure (True/False)
TriggerRed: True               # Include Red CCD in exposure (True/False)
BlockSky: False                # Close the sky fiber shutter during observations (True/False)
# Exposure Meter 
ExpMeterMode: control          # "monitor" or "control" (to terminate exposure based on flux)
AutoExpMeter: False            # Set the exposure meter exposure time automatically
ExpMeterExpTime: 0.5           # Exposure time of the Exposure Meter subframes
ExpMeterBin: 3                 # Exposure meter wavelength bin to use for stopping exposure
ExpMeterThreshold: 1e5         # Target science flux in e-/nm
# Simultaneous Calibration 
TakeSimulCal: True             # Take simultaneous calibrations? (True/False)
AutoNDFilters: False           # Automatically set ND filters
CalND1: OD 4.0                 # OD=Optical Density. Throughput = 10^-OD. Values = OD 0.1, OD 1.0, OD 1.3, OD 2.0, OD 3.0, OD 4.0
CalND2: OD 0.1                 # Values: OD 0.1, OD 0.3, OD 0.5, OD 0.8, OD 1.0, OD 4.0
